// react/src/components/Cart.jsx
import { Link } from 'react-router-dom';
import './cart.css';
import * as Sentry from '@sentry/react';
import Button from './ButtonLink';
import { connect } from 'react-redux';
import { setProducts, addProduct, removeProduct } from '../actions';
import { countItemsInCart } from '../utils/cart';
import { getTag } from '../utils/utils';


function Cart({ cart, removeProduct, addProduct }) {
  const itemsInCart = countItemsInCart(cart);
  let tags = { 'backendType': getTag('backendType'), 'cexp': getTag('cexp'), 'items_in_cart': itemsInCart };
  const span = Sentry.startInactiveSpan({ name: "items_added_to_cart", op: "function"});
  span.setAttributes(tags);
  span.end();
  Sentry.metrics.gauge("items_in_cart", itemsInCart);
  return (
    <div className="cart-container">
      <h2 className="sentry-unmask">Cart</h2>
      {cart.items.length > 0 ? (
        <>
          <ul className="cart-list">
            {cart.items.map((item) => {
              const quantity = cart.quantities[item.id];
              const itemLink = '/product/' + item.id;
              return (
                <li className="cart-item" key={item.id}>
                  <Link to={itemLink}>
                    <img
                      src={item.img}
                      alt="item-thumbnail"
                      className="sentry-block"
                    />
                  </Link>
                  <Link to={itemLink}>
                    <h4>{item.title}</h4>
                  </Link>
                  <p>
                    <span className="sentry-unmask">$</span>
                    {item.price}.00
                  </p>
                  <div className="quantity-adjust">
                    <button
                      onClick={() => removeProduct(item)}
                      className="sentry-unmask"
                    >
                      –
                    </button>
                    <span>{quantity}</span>
                    <button
                      onClick={() => addProduct(item)}
                      className="sentry-unmask"
                    >
                      +
                    </button>
                  </div>
                  <p>
                    <span className="sentry-unmask">$</span>
                    {item.price * quantity}.00
                  </p>
                </li>
              );
            })}
          </ul>
          <h3 className="cart-subtotal">
            <span className="sentry-unmask">Cart Subtotal: $</span>
            {cart.total}.00
          </h3>
          <Button to="/checkout-form" className="sentry-unmask">
            Proceed to checkout
          </Button>
        </>
      ) : (
        <p>Please add items to the cart</p>
      )}
    </div>
  );
}

const mapStateToProps = (state, ownProps) => {
  return {
    cart: state.cart,
    products: state.products,
  };
};

export default connect(mapStateToProps, {
  setProducts,
  addProduct,
  removeProduct,
})(Sentry.withProfiler(Cart, { name: 'Cart' }));

// angular/src/app/components/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { CartService, CartState, CartItem } from '../../services/cart.service';
import { getTag } from '../../utils/sentry-utils';
import * as Sentry from '@sentry/angular';
import { metrics } from '@sentry/browser';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {
  cart: CartState = { items: [], quantities: {}, total: 0 };

  constructor(private cartService: CartService) {}

  ngOnInit(): void {
    this.cartService.cart$.subscribe(cart => {
      this.cart = cart;
      this.emitCartMetrics();
    });
  }

  private emitCartMetrics(): void {
    const itemsInCart = this.cartService.getCartItemCount();
    const tags: Record<string, any> = {
      'backendType': getTag('backendType'),
      'cexp': getTag('cexp'),
      'items_in_cart': itemsInCart,
    };
    const span = Sentry.startInactiveSpan({ name: 'items_added_to_cart', op: 'function' });
    span.setAttributes(tags);
    span.end();
    metrics.distribution('items_in_cart', itemsInCart);
  }

  addProduct(item: CartItem): void {
    this.cartService.addCartItem(item);
  }

  removeProduct(item: CartItem): void {
    this.cartService.removeCartItem(item);
  }

  getQuantity(itemId: number): number {
    return this.cart.quantities[itemId] || 0;
  }

  getItemTotal(item: CartItem): number {
    const quantity = this.cart.quantities[item.id] || 0;
    return item.price * quantity;
  }
}

<div class="cart-container">
  <h2 class="sentry-unmask">Cart</h2>
  
  <div *ngIf="cart.items.length > 0">
    <ul class="cart-list">
      <li *ngFor="let item of cart.items" class="cart-item">
        <a [routerLink]="['/product', item.id]">
          <img [src]="item.img" [alt]="item.title" class="sentry-block" />
        </a>
        <a [routerLink]="['/product', item.id]">
          <h4>{{ item.title }}</h4>
        </a>
        <p>
          <span class="sentry-unmask">$</span>{{ item.price }}.00
        </p>
        <div class="quantity-adjust">
          <button
            (click)="removeProduct(item)"
            class="sentry-unmask"
          >
            –
          </button>
          <span>{{ cart.quantities[item.id] || 0 }}</span>
          <button
            (click)="addProduct(item)"
            class="sentry-unmask"
          >
            +
          </button>
        </div>
        <p>
          <span class="sentry-unmask">$</span>{{ item.price * (cart.quantities[item.id] || 0) }}.00
        </p>
      </li>
    </ul>
    
    <h3 class="cart-subtotal">
      <span class="sentry-unmask">Cart Subtotal: $</span>{{ cart.total }}.00
    </h3>
    
    <a routerLink="/checkout-form" class="btn sentry-unmask">
      Proceed to checkout
    </a>
  </div>
  
  <div *ngIf="cart.items.length === 0">
    <p>Please add items to the cart</p>
  </div>
</div>
