// react/src/components/Complete.jsx
import { Link } from 'react-router-dom';
import './complete.css';
import { useSelector } from 'react-redux';

function Complete({cart, resetCart}) {
  const cart = useSelector((state) => state.cart);

  useEffect(() => {
    window.setTimeout(() => {
      Sentry.getReplay().flush();
    }, 1000);
  });

  const RandomNumber = Math.floor(Math.random() * 99999) + 10000;

  return (
    <div className="checkout-container-complete">
      <h2>Checkout complete</h2>
      <h4>
        Order No: {RandomNumber} — Total: ${cart.total}.00
      </h4>
      <p>A confirmation email has been sent to the address you provided.</p>
      <p>
        Your plants will thank you. You can <Link to="/">track your order</Link>{' '}
        or <Link to="/">contact us</Link> if you have any questions. Have a
        sunny day.
      </p>
    </div>
  );
}

export default Complete;

// angular/src/app/components/complete/complete.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { CartService, CartState } from '../../services/cart.service';
import * as Sentry from '@sentry/angular';

@Component({
  selector: 'app-complete',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './complete.component.html',
  styleUrls: ['./complete.component.css']
})
export class CompleteComponent implements OnInit {
  orderedCart: CartState = { items: [], quantities: {}, total: 0 };
  orderNumber: number = 0;

  constructor(private cartService: CartService) {}

  ngOnInit() {
    // Get current cart state
    this.cartService.cart$.subscribe(cart => {
      this.orderedCart = cart;
    });

    // Generate random order number (like React)
    this.orderNumber = Math.floor(Math.random() * 99999) + 10000;

    // Reset cart after successful checkout (like React)
    this.cartService.resetCart();

    // Handle replay flush exactly like React
    window.setTimeout(() => {
      const replay = Sentry.getReplay();
      if (replay) {
        replay.flush();
      }
    }, 1000);
  }
}

<div class="checkout-container-complete">
  <h2>Checkout complete</h2>
  <h4>
    Order No: {{ orderNumber }} — Total: ${{ orderedCart.total }}.00
  </h4>
  <p>A confirmation email has been sent to the address you provided.</p>
  <p>
          Your plants will thank you. You can <a routerLink="/" href="/">track your order</a> or
      <a routerLink="/" href="/">contact us</a> if you have any questions. Have a sunny day.
  </p>
</div>
