// angular/src/app/components/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { employees } from '../../data/employees';
import { slugify } from '../../utils/slugify';
import { ConfigService } from '../../services/config.service';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {
  employees = employees;

  constructor(private router: Router, private configService: ConfigService) {}

  ngOnInit() {
    // Mirror React's additional API calls for performance optimization
    this.makeAdditionalApiCalls();
    
    // Mirror React's busy_sleep logic (simplified version)
    if (!this.isOddReleaseWeek()) {
      this.busySleep(Math.random() * 25 + 100);
    }
  }

  /**
   * Makes additional API calls to test backend connectivity
   * These are expected to fail and demonstrate error handling
   */
  private async makeAdditionalApiCalls() {
    // Use config service for backend URL (supports Laravel/Flask switching)
    const backendUrl = this.configService.getBackendUrl();
    const backendType = this.configService.getCurrentBackendType();
    
    
    const endpoints = ['/api', '/organization', '/connect'];
    
    for (const endpoint of endpoints) {
      try {
        const response = await fetch(backendUrl + endpoint, {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' }
        });
        
        if (!response.ok) {
        }
      } catch (err) {
      }
    }
  }

  // Mirror React's isOddReleaseWeek logic (simplified)
  private isOddReleaseWeek(): boolean {
    const now = new Date();
    const weekNumber = Math.ceil((now.getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / (7 * 24 * 60 * 60 * 1000));
    return weekNumber % 2 === 1;
  }

  // Mirror React's busy_sleep logic (simplified)
  private busySleep(ms: number) {
    const start = Date.now();
    while (Date.now() - start < ms) {
      // Busy wait
    }
  }

  // Navigate to employee detail page
  onEmployeeClick(employee: any) {
    const slug = slugify(employee.url);
    this.router.navigate(['/employee', slug], { state: employee });
  }

  // TrackBy function for ngFor optimization
  trackByEmployee(index: number, employee: any): string {
    return employee.name;
  }
}

<div class="about-page">
  <div>
    <div class="about-info">
      <h1>About us</h1>
      <p>
        Empower Plant is an IoT company determined to keep house plants
        happy. After reading Michael Pollan's 2013 New Yorker article ("The
        Intelligent Plant"), the wife-and-wife founding team invested their
        life savings in measuring and improving the emotional state of their
        leafy housemates. Seven years later, the company's grown from its
        humble roots in the couples' backyard greenhouse (converted from a
        garage) into a Series C-funded San Francisco startup and the world's
        most accurate plant mood measurer ("a must-have for any responsible
        plant parent," according to Plant Parenthood Magazine). Their
        original state-of-the-art product is a technological marvel built
        with a plant-first mindset, and they now offer a range of
        plant-centric options.
      </p>
      <p>
        Today, the company employs 170 people (and 852 plants) in San
        Francisco, New York City, Denver, and Kiev.
      </p>
    </div>
  </div>
  <div>
    <ul class="employee-list">
      <li *ngFor="let employee of employees; trackBy: trackByEmployee">
        <div (click)="onEmployeeClick(employee)" class="employee-link">
          <img [src]="employee.img" [alt]="employee.name" />
          <h5 class="employee-name" [attr.name]="employee.name">
            {{ employee.name }}
          </h5>
        </div>
      </li>
    </ul>
  </div>
</div>

// react/src/components/About.js
import { Component } from 'react';
import { Link } from 'react-router-dom';
import slugify from '../utils/slugify';
import * as Sentry from '@sentry/react';
import './about.css';

import Jane from './employees/jane';
import Lily from './employees/lily';
import Keith from './employees/keith';
import Mason from './employees/mason';
import Emma from './employees/emma';
import Noah from './employees/noah';

const employees = [Jane, Lily, Keith, Mason, Emma, Noah];

class About extends Component {
  render() {
    return (
      <div className="about-page">
        <div>
          <div className="about-info">
            <h1>About us</h1>
            <p>
              Empower Plant is an IoT company determined to keep house plants
              happy. After reading Michael Pollan’s 2013 New Yorker article
              (“The Intelligent Plant”), the wife-and-wife founding team
              invested their life savings in measuring and improving the
              emotional state of their leafy housemates. Seven years later, the
              company’s grown from its humble roots in the couples’ backyard
              greenhouse (converted from a garage) into a Series C-funded San
              Francisco startup and the world’s most accurate plant mood
              measurer (“a must-have for any responsible plant parent,”
              according to Plant Parenthood Magazine). Their original
              state-of-the-art product is a technological marvel built with a
              plant-first mindset, and they now offer a range of plant-centric
              options.
            </p>
            <p>
              Today, the company employs 170 people (and 852 plants) in San
              Francisco, New York City, Denver, and Kiev.
            </p>
          </div>
        </div>
        <div>
          <ul className="employee-list">
            {employees.map((employee) => {
              return (
                <li key={employee.name}>
                  <Link to={`/employee/${slugify(employee.url)}`}>
                    <img src={employee.img} alt={`${employee.name}`} />
                    <h5 className="employee-name" name={employee.name}>{employee.name}</h5>
                  </Link>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    );
  }
}

export default Sentry.withProfiler(About, { name: "About"})
