// angular/src/app/components/complete-error/complete-error.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import * as Sentry from '@sentry/angular';

@Component({
  selector: 'app-complete-error',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './complete-error.component.html',
  styleUrls: ['./complete-error.component.css']
})
export class CompleteErrorComponent implements OnInit {

  constructor() {}

  ngOnInit() {
    // Flush replay like React
    window.setTimeout(() => {
      const replay = Sentry.getReplay();
      if (replay) {
        replay.flush();
      }
    }, 1000);
  }

  // Handle feedback button click
  onFeedbackClick() {
    // In a real implementation, this would show a feedback dialog
  }

  // Handle contact us button click (like React)
  onContactUsClick() {
    // In a real implementation, this would open a contact form
  }
}

<div class="checkout-container-complete">
  <h2>We're having some trouble</h2>
  <p>
    We were unable to process your order but will do everything we can to
    make it right. Please <a href="#">reach out to us</a> if you have
    been charged or have any questions.
  </p>
  <button id="contact-us">Contact Us</button>
</div>

// react/src/components/CompleteError.js
import { Link } from 'react-router-dom';
import './complete.css';
import * as Sentry from '@sentry/react';
import { useEffect } from 'react';

function CompleteError() {
  useEffect(() => {
    window.setTimeout(() => {
      if (sessionStorage.getItem('userFeedback') === 'true') {
        sessionStorage.removeItem('userFeedback');
        if (sessionStorage.getItem('lastErrorEventId')) {
          Sentry.showReportDialog({
            eventId: sessionStorage.getItem('lastErrorEventId'),
          });
        } else {
          console.log(
            'No error event id found, not showing User Feedback report dialog'
          );
        }
      }
    }, 3500);
  });

  return (
    <div className="checkout-container-complete sentry-unmask">
      <h2>We're having some trouble</h2>
      <p>
        We were unable to process your order but will do everything we can to
        make it right. Please <Link to="#">reach out to us</Link> if you have
        been charged or have any questions.
      </p>
      <button id="contact-us"></button>
    </div>
  );
}

export default CompleteError;
