// angular/src/app/components/checkout/checkout.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CartService, CartState, CartItem } from '../../services/cart.service';
import { Product } from '../../services/products.service';
import { ConfigService, CheckoutForm } from '../../services/config.service';
import { ThreeDotsComponent } from '../three-dots/three-dots.component';
import * as Sentry from '@sentry/angular';

/**
 * Checkout Component - Handles the final purchase process
 * 
 * This component manages the checkout form and submission process:
 * - Displays a pre-filled checkout form with user information
 * - Handles form validation and submission
 * - Integrates with Sentry for error monitoring
 * - Manages the checkout flow and error handling
 * 
 * Key Features:
 * - Pre-filled form data for demo purposes
 * - Form validation and error handling
 * - Sentry integration for monitoring
 * - Cart state management
 * 
 * TDA Test Compatibility:
 * - Form structure matches React app for automated testing
 * - Button classes and IDs are consistent across frameworks
 * - Form submission flow mirrors React implementation
 */
@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, ThreeDotsComponent],
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.css']
})
export class CheckoutComponent implements OnInit {
  // Current cart state (items, quantities, total)
  cart: CartState = { items: [], quantities: {}, total: 0 };
  
  // Form data object for checkout information
  form: CheckoutForm = {
    email: '',
    subscribe: '',
    firstName: '',
    lastName: '',
    address: '',
    city: '',
    country: '',
    state: '',
    zipCode: ''
  };

  // Loading state for smooth checkout experience (like React)
  loading = false;

  constructor(
    private cartService: CartService,
    private configService: ConfigService,
    private router: Router
  ) {}

  ngOnInit(): void {
    // Subscribe to cart updates and load form data when component initializes
    this.cartService.cart$.subscribe(cart => {
      this.cart = cart;
    });
    
    // Load pre-filled form data for demo purposes
    this.loadFormData();
  }

  /**
   * Loads pre-filled form data from the configuration service
   * This provides demo data so users don't have to type everything
   */
  loadFormData(): void {
    // Get pre-filled form values from the config service
    this.form = this.configService.getInitialFormValues();
  }

  /**
   * Handles form submission when user clicks "Complete order"
   * Processes the checkout and handles any errors
   * Mirrors React's checkout behavior for TDA compatibility
   * The checkout will intentionally fail to showcase Sentry error monitoring
   * 
   * @param event - The form submission event
   */
  async onSubmit(event: Event): Promise<void> {
    // Prevent the default form submission behavior
    event.preventDefault();

    // Check if rage click mode is enabled (like React)
    if (this.configService.getRageclick()) {
      // Do nothing - after enough clicks, this will be detected as unusual behavior
      return;
    }

    // Scroll to top (like React)
    window.scrollTo({
      top: 0,
      behavior: 'auto'
    });

    // Set loading state for smooth experience (like React)
    this.loading = true;

    try {
      // Process the checkout (this will intentionally fail to showcase Sentry)
      await this.processCheckout();
      
      // If successful, navigate to complete page (like React)
      this.router.navigate(['/complete']);
    } catch (error) {
      // This is the expected behavior - checkout fails to showcase Sentry
      console.error('Checkout error (expected for demo):', error);
      
      // Capture the error in Sentry for monitoring (this is the demo highlight)
      Sentry.captureException(error, {
        tags: {
          component: 'checkout',
          action: 'form_submission'
        },
        extra: {
          cart: this.cart,
          form: this.form
        }
      });
      
      // Navigate to error page to show the error (like React)
      this.router.navigate(['/error']);
    } finally {
      // Always reset loading state
      this.loading = false;
    }
  }

  /**
   * Makes actual API call to backend like React does
   * The backend will intentionally fail to showcase Sentry error monitoring
   * 
   * @returns Promise<Response> - The checkout API response
   */
  private async processCheckout(): Promise<Response> {
    
    const itemsInCart = this.cartService.getCartItemCount();

    // Get backend URL from config service (supports Laravel/Flask switching)
    const backendUrl = this.configService.getBackendUrl();
    const backendType = this.configService.getCurrentBackendType();
    const checkoutUrl = `${backendUrl}/checkout?v2=true`;
    

    const requestBody = {
      cart: this.cart,
      form: this.form,
      validate_inventory: this.configService.getCheckoutSuccess() ? "false" : "true"
    };


    try {
      const response = await fetch(checkoutUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody)
      });

      if (!response.ok) {
        console.error("Checkout failed with status:", response.status);
        const error = new Error(`${response.status} - ${response.statusText || 'Internal Server Error'}`);
        
        // Send HTTP error to Sentry (this is the demo highlight)
        Sentry.captureException(error, {
          tags: {
            component: 'checkout',
            action: 'api_call',
            http_status: response.status.toString()
          },
          extra: {
            url: checkoutUrl,
            status: response.status,
            statusText: response.statusText,
            requestBody: requestBody
          }
        });
        
        throw error;
      }

      return response;
    } catch (error) {
      console.error("Checkout request failed:", error);
      throw error;
    }
  }

  /**
   * Gets the current quantity of a specific product in the cart
   * Returns 0 if the product is not in the cart
   * 
   * @param itemId - The ID of the product to get quantity for
   * @returns The current quantity (0 if not in cart)
   */
  getQuantity(itemId: number): number {
    return this.cart.quantities[itemId] || 0;
  }
}

<div class="checkout-container">
  <h2 class="sentry-unmask">Checkout</h2>
  
  <!-- Loading State -->
  <div *ngIf="loading" class="loader-container">
    <app-three-dots color="#f6cfb2" [height]="150" [width]="150"></app-three-dots>
  </div>
  
  <!-- Checkout Form (hidden when loading) -->
  <div *ngIf="!loading && cart.items.length > 0">
    <!-- Checkout Form -->
    <form class="checkout-form" (ngSubmit)="onSubmit($event)">
      <h4 class="sentry-unmask">Contact Information</h4>
      
      <label for="email" class="sentry-unmask">Email</label>
      <input
        id="email"
        name="email"
        type="email"
        [(ngModel)]="form.email"
        placeholder="bob@example.com"
        required
      />

      <h4 class="sentry-unmask">Shipping Information</h4>
      
      <label for="firstName" class="sentry-unmask">First Name</label>
      <input
        id="firstName"
        name="firstName"
        type="text"
        [(ngModel)]="form.firstName"
        placeholder="Bob"
        required
      />

      <label for="lastName" class="sentry-unmask">Last Name</label>
      <input
        id="lastName"
        name="lastName"
        type="text"
        [(ngModel)]="form.lastName"
        placeholder="Bobson"
        required
      />

      <label for="address" class="sentry-unmask">Address</label>
      <input
        id="address"
        name="address"
        type="text"
        [(ngModel)]="form.address"
        placeholder="123 Main Street"
        required
      />

      <label for="city" class="sentry-unmask">City</label>
      <input
        id="city"
        name="city"
        type="text"
        [(ngModel)]="form.city"
        placeholder="Hope Springs"
        required
      />

      <label for="country" class="sentry-unmask">Country/Region</label>
      <input
        id="country"
        name="country"
        type="text"
        [(ngModel)]="form.country"
        placeholder="United States of America"
        required
      />

      <label for="state" class="sentry-unmask">State</label>
      <input
        id="state"
        name="state"
        type="text"
        [(ngModel)]="form.state"
        placeholder="Indiana"
        required
      />

      <label for="zipCode" class="sentry-unmask">Zip Code</label>
      <input
        id="zipCode"
        name="zipCode"
        type="text"
        [(ngModel)]="form.zipCode"
        placeholder="45678"
        required
      />

      <input
        type="submit"
        class="complete-checkout-btn sentry-unmask"
        value="Complete order"
      />
    </form>
    
    <a routerLink="/cart" class="sentry-unmask">
      Back to cart
    </a>
  </div>
  
  <div *ngIf="cart.items.length === 0">
    <p>Your cart is empty. Please add items before checkout.</p>
    <a routerLink="/products" class="btn">Browse Products</a>
  </div>
</div>

// next/src/pages/checkout.jsx
import React, { useState } from 'react';
import Link from 'next/link';
import measureRequestDuration from '../utils/measureRequestDuration';
import * as Sentry from '@sentry/nextjs';
import { connect } from 'react-redux';
import Loader from 'react-loader-spinner';
import { useRouter } from 'next/router';
import {
  determineBackendType,
  determineBackendUrl,
} from '../utils/backendrouter';

function Checkout({ rageclick, cart }) {
  const router = useRouter();
  const { backend, se } = router.query;
  const backendType = determineBackendType(backend);
  const backendUrl = determineBackendUrl(backendType);
  const [loading, setLoading] = useState(false);
  let initialFormValues;
  if (se && se.startsWith('prod-tda-')) {
    // we want form actually filled out in TDA for a realistic-looking Replay
    initialFormValues = {
      email: '',
      subscribe: '',
      firstName: '',
      lastName: '',
      address: '',
      city: '',
      country: '',
      state: '',
      zipCode: '',
    };
  } else {
    initialFormValues = {
      email: 'plant.lover@example.com',
      subscribe: '',
      firstName: 'Jane',
      lastName: 'Greenthumb',
      address: '123 Main Street',
      city: 'San Francisco',
      country: 'United States of America',
      state: 'CA',
      zipCode: '94122',
    };
  }
  const [form, setForm] = useState(initialFormValues);

  async function checkout(cart) {
    Sentry.metrics.increment('checkout.click');
    const stopMeasurement = measureRequestDuration('/checkout');
    const response = await fetch(backendUrl + '/checkout?v2=true', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Se: se },
      body: JSON.stringify({
        cart: cart,
        form: form,
      }),
    })
      .catch((err) => {
        Sentry.metrics.increment('checkout.error', 1, {
          tags: { status: 500 },
        });
        return { ok: false, status: 500 };
      })
      .then((res) => {
        stopMeasurement();
        return res;
      });
    if (!response.ok) {
      Sentry.metrics.increment('checkout.error', 1, {
        tags: { status: response.status },
      });
      throw new Error(
        [response.status, response.statusText || ' Internal Server Error'].join(
          ' -'
        )
      );
    }
    Sentry.metrics.increment('checkout.success');
    Sentry.metrics.distribution('checkout.order.total', cart.total);
    return response;
  }
  function generateUrl(product_id) {
    return product_id;
  }

  function handleInputChange(event) {
    const target = event.target;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const name = target.name;
    setForm({ ...form, [name]: value });
  }

  async function handleSubmit(event) {
    event.preventDefault();

    if (rageclick) {
      // do nothing. after enough clicks,
      // Sentry will detect a rageclick
      return;
    }

    Sentry.startSpan(
      {
        name: 'Submit Checkout Form',
        forceTransaction: true,
      },
      async (span) => {
        let hadError = false;

        window.scrollTo({
          top: 0,
          behavior: 'auto',
        });

        setLoading(true);

        try {
          await checkout(cart);
        } catch (error) {
          console.log('had error');
          Sentry.captureException(error);
          hadError = true;
        }
        setLoading(false);

        if (hadError) {
          router.push('/completeError');
        } else {
          router.push('/complete');
        }
      }
    );
  }

  return (
    <div className="checkout-container">
      {loading ? (
        <Loader
          type="ThreeDots"
          color="#f6cfb2"
          className="sentry-unmask"
          height={150}
          width={150}
        />
      ) : (
        <>
          <h2 className="sentry-unmask">Checkout</h2>
          <form className="checkout-form" onSubmit={handleSubmit}>
            <h4 className="sentry-unmask">Contact information</h4>

            <label htmlFor="email" className="sentry-unmask">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="email"
              onChange={handleInputChange}
              defaultValue={form.email}
              placeholder="joebobson@joeb.com"
            />

            <input
              id="subscribe"
              name="subscribe"
              type="checkbox"
              onChange={handleInputChange}
              defaultValue={form.subscribe}
            />
            <label htmlFor="subscribe" className="sentry-unmask">
              Keep me updated with new sales and products
            </label>

            <h4 className="sentry-unmask">Shipping address</h4>
            <label htmlFor="firstName" className="sentry-unmask">
              First Name
            </label>
            <input
              id="firstName"
              name="firstName"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.firstName}
              placeholder="Joe"
              className="half-width"
            />
            <label htmlFor="lastName" className="sentry-unmask">
              Last Name
            </label>
            <input
              id="lastName"
              name="lastName"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.lastName}
              placeholder="Bobson"
            />

            <label htmlFor="address" className="sentry-unmask">
              Address
            </label>
            <input
              id="address"
              name="address"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.address}
              placeholder="123 Main Street"
            />

            <label htmlFor="city" className="sentry-unmask">
              City
            </label>
            <input
              id="city"
              name="city"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.city}
              placeholder="Hope Springs"
            />

            <label htmlFor="country" className="sentry-unmask">
              Country/Region
            </label>
            <input
              id="country"
              name="country"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.country}
              placeholder="United States of America"
            />

            <label htmlFor="state" className="sentry-unmask">
              State
            </label>
            <input
              id="state"
              name="state"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.state}
              placeholder="Indiana"
            />

            <label htmlFor="zipCode" className="sentry-unmask">
              Zip Code
            </label>
            <input
              id="zipCode"
              name="zipCode"
              type="text"
              onChange={handleInputChange}
              defaultValue={form.zipCode}
              placeholder="45678"
            />

            <input
              type="submit"
              className="complete-checkout-btn sentry-unmask"
              defaultValue="Complete order"
            />
          </form>
          <Link href="/cart" className="sentry-unmask">
            Back to cart
          </Link>
        </>
      )}
    </div>
  );
}

const mapStateToProps = (state, ownProps) => {
  return {
    cart: state.cart,
    products: state.products,
  };
};

export default connect(mapStateToProps, {})(Checkout);
